### ISSUE TITLE
support for multiple addresses

### ISSUE THREAD

**Issue by szczys** [adamgreen/i2cperipheral#1]
Great driver, thanks for publishing this!

I'd like to use this driver to listen on two different addresses (for instance: 0x12 for commands and 0x13 for data). I tried to instantiate two devices but it seems that only the most recently created device listens for its address.

Is there any support for this currently in place?

**Comment by adamgreen** [comment]
I certainly didn't write it to support that functionality. I see that my code just gives the address to the Pico C SDK when it sets the peripheral to slave mode: https://github.com/adamgreen/i2cperipheral/blob/master/CI2CPeripheral.c#L162

It's been awhile since I read the RP2040 data sheet but I don't have a memory of the hardware actually supporting that either. 

If you think of most I2C devices working like 'memory mapped' hardware where the first byte sent to a specific I2C during a read or write transaction is the 'memory' address and the rest of the bytes are the value(s) to be placed starting at that address then using different 'memory' addresses would be the way to distinguish between commands and data.

**Comment by szczys** [comment]
Thanks for the reply, I see now the Pico-SDK limitation on assigning the address.

I had previously implemented a peripheral device using this driver that listened for a variable number of bytes after a register address. For instance, sending "Temperature" to address 0x15 would look like this:

```
[ 0x15 0x54 0x65 0x6d 0x70 0x65 0x72 0x61 0x74 0x75 0x72 0x65 ]
```

However, (and this may be due to the sender) I was often getting that string in two bursts (both to the correct device address) like this:

```
[ 0x15 0x54 0x65 0x6d 0x70 0x65 0x72 0x61 0x74 ]
[ 0x75 0x72 0x65 ]
```

And so the device would think that the second burst was a new command at register address `0x75`. If there some change I can make to how I'm using your driver to overcome this issue, I'd be very happy for any advice!

My idea for using two addresses is that every command would then be the register address with no other bytes so the split messages would not be an issue. On the data address, bytes are accumulated until the next command is received (again, split messages are not a problem this way).

Today I've implemented this using [a PIO/Interrupt based driver](https://github.com/dgatf/I2C-slave-multi-address-RP2040) by @dgatf and it seems to be working well. Although I do still need to get it working with micropython.

**Comment by adamgreen** [comment]
When I look at how this driver is organized, it looks like if you ask it to receive N bytes from the master in the recv() call then it will raise a MP_ETIMEDOUT OSError exception instead of returning less than the number of bytes that you expected. So in this split example of yours:
```
[ 0x15 0x54 0x65 0x6d 0x70 0x65 0x72 0x61 0x74 ]
[ 0x75 0x72 0x65 ]
```
I don't understand how the first packet has only 9 bytes when it expected 12 bytes. That should have resulted in a timeout exception. Maybe instead you asked for a byte at time from my driver until you got a timeout? If so then it could have been caused by it taking a little too long for your master to send the last 3 bytes.

**Comment by szczys** [comment]
Apologies for the delay in replying to you. I've continued to test the issues and today I found it was caused by a bad cable interconnecting the i2c bus between two boards. Now that I've replaced the cable I can send strings of arbitrary length and they are received as a single message using this driver.

**Comment by adamgreen** [comment]
That would explain it. The code didn't look like it should do that.

**Comment by adamgreen** [comment]
Thanks for investigating it further and letting me know the results.
